# Generated by Django 2.2.6 on 2019-10-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=0, verbose_name='Time you started driving')),
                ('end_date', models.DateTimeField(default=0, verbose_name='Time you ended driving')),
            ],
        ),
    ]
